services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PayFlow_Strong_Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - payflow-sqlserver-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: payflow-api
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PayFlow;User Id=sa;Password=PayFlow_Strong_Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  payflow-sqlserver-data:
